### ISSUE TITLE
Moving to libmir

### ISSUE THREAD

**Issue by wilzbach** [libmir/numir#11]
Seeing that this project gains in importance, how do you feel about moving it to the libmir organization?
It would be great in terms of managing permissions and foster the visibility to the public.

If you want to do so, I think you first need to transfer it to an admin (e.g. @9il or myself).

CC @9il @jmh530

**Comment by jmh530** [comment]
The documentation for numir is not yet at the level of some of the other mir projects.

**Comment by wilzbach** [comment]
> The documentation for numir is not yet at the level of some of the other mir projects.

This shouldn't block us?
On the contrary: by setting up a documentation CI, the problem becomes more visible :)

**Comment by jmh530** [comment]
@wilzbach Great. That was my only concern.

**Comment by ShigekiKarita** [comment]
@wilzbach thank you for this invitation.
As @jmh530 mentioned, first we want to enrich the documentation and also CI.
Then, I will transfer this project to libmir!

**Comment by wilzbach** [comment]
> first we want to enrich the documentation and also CI.

I am happy to help out with both (e.g. doing a similar setup as on Mir), but it's quite a pain with the AWS credentials and buckets, so I would like to do this only once.

**Comment by 9il** [comment]
> The documentation for numir is not yet at the level of some of the other mir projects.

We only need to setup travis, dub and appveyor. Documentation is not a blocker.

**Comment by ShigekiKarita** [comment]
I've just setup the travis (doc generation) and appveyor today #12 
Then I referred to appveyor.yml in dfmt by @wilzbach, thanks!

**Comment by 9il** [comment]
@ShigekiKarita I have sent invitation to you. You have the full powers to move the repo yourself. Do not forget to update dub registry.

**Comment by ShigekiKarita** [comment]
@9il Thanks! I will do it on this weekend.

**Comment by ShigekiKarita** [comment]
Today, I finished moving to mir.

+ Travis ([test](https://travis-ci.org/libmir/numir) & [doc](https://libmir.github.io/numir/index.html)): automatically enabled
+ [Coveralls](https://coveralls.io/github/libmir/numir): manually enabled
+ [Appveyor](https://ci.appveyor.com/project/ShigekiKarita/numir-f7jog): manually enabled
+ [DUB](https://code.dlang.org/packages/numir): manually updated

**Comment by 9il** [comment]
Awesome, thank you!
