### ISSUE TITLE
Squeeze Does Not Match Numpy Functionality

### ISSUE THREAD

**Issue by jmh530** [libmir/numir#17]
The unittest for squeeze
```
    assert(iota(1, 3, 4).slice.squeeze!0.shape == [3, 4]);
    assert(iota(3, 1, 4).slice.squeeze!1.shape == [3, 4]);
    assert(iota(3, 4, 1).slice.squeeze!(-1).shape == [3, 4]);
```
shows it being used with specific values for `a`.

The way Numpy's squeeze works is that it removes all 1-dimensional indices, or a subset.

This suggests that to match Numpy's functionality would require additional overloads, such as 
```
auto squeeze(S)(S s) pure
```
that would remove all and 
```
auto squeeze(Slice sl, S)(S s) pure
```
where `sl` is a slice indicative of a subset. Admittedly the first is more important than the second.

**Comment by ShigekiKarita** [comment]
It is difficult to implement because there is a dynamic return type mismatch of packs as follows:
``` d
auto squeeze(S s) pure // if S.packs = [N]
{
    foreach (i, n; s.shape) {
        if (n == 1) {
            return squeeze(s, i).squeeze; // packs = [M] where M < N
        }
    }
    return s; // packs = [N]
}
```

**Comment by jmh530** [comment]
@ShigekiKarita The tricky part is that it returns a view of `a` rather than returning a new slice, in which case you could just use `reshape`. 

Perhaps @9il has any suggestions?

**Comment by 9il** [comment]
Lets make `squeeze` accept only one CT parameter - the number of the result dimensions.
Algorithm should copy all non `1`dimensions from back to front and fill remaining dimensions with `1` . `Contiguous` -> `Contiguous`, other -> `Universal`

**Comment by jmh530** [comment]
`squeeze` in mir-algorithm has this functionality.
